; Generated by render_configs.py from conf/stream.json
[supervisord]
nodaemon=true
logfile=/dev/null
loglevel=info
pidfile=/var/run/op25/supervisord.pid
childlogdir=/var/log/op25
minfds=1024

[unix_http_server]
file=/var/run/op25/supervisor.sock
chmod=0700

[inet_http_server]
port=127.0.0.1:9001
username=op25
password=@SUPERVISOR_PASSWORD@

[supervisorctl]
serverurl=unix:///var/run/op25/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:op25]
command=/usr/bin/python3 /opt/op25/apps/multi_rx.py -v @OP25_VERBOSITY@ -c /opt/op25/conf/cfg.json
directory=/opt/op25/apps
priority=100
autorestart=true
startretries=999
startsecs=1
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/op25/op25.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=4

[program:streams]
command=/opt/op25/venv/bin/python /opt/op25/stream_runner.py
directory=/opt/op25
priority=200
autorestart=true
startretries=999
startsecs=1
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/op25/streams.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=4

[program:icecast]
command=/usr/bin/icecast2 -c /etc/op25/icecast.xml
directory=/tmp
priority=300
autorestart=true
startretries=999
startsecs=1
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/op25/icecast.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=4

[program:web]
command=/opt/op25/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8080 --no-access-log
directory=/opt/op25/control-plane
priority=50
autorestart=true
startretries=999
startsecs=1
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/op25/web.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=4
environment=OP25_CONF_DIR="/opt/op25/conf",OP25_APPS_DIR="/opt/op25/apps",OP25_TERM_PORT="5600",OP25_STREAM="primary"
